### ISSUE TITLE
Turn metadata tab into tableview

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#103]
Considering the structure of the metadata dictionary (pv, desc, unit, value), it would be easy to make it a nice tableview:
```yml
- - - sampleEntry
    - description: description
      unit: unit string
      value: value
 - - 29idARPES:saveData_fileName
    - description: File Name
      unit: ''
      value: mda_0006.mda
  - - 29idARPES:saveData_fileSystem
    - description: File System
      unit: ''
      value: /net/s29data/export/data_29idc/2020_2
```

Only one entry will need to be handled differently (`QLabel`?), and I am guessing some fo this info is not is really needed (mda object key for example): 

```yml
  - - filename
    - !!python/object/apply:pathlib.PosixPath
      - /
      - Users
      - fannysimoes
      - src
      - mdaviz
      - mdaviz
      - data
      - test_folder1
      - mda_0006.mda
  - - version
    - 1.2999999523162842
  - - scan_number
    - 6
  - - rank
    - 1
  - - dimensions
    - - 21
  - - acquired_dimensions
    - - 21
  - - isRegular
    - 1
  - - ourKeys
    - - sampleEntry
      - filename
      - version
      - scan_number
      - rank
      - dimensions
      - acquired_dimensions
      - isRegular
      - ourKeys
```
