### ISSUE TITLE
Contribute mdaviz to conda-forge.

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/mdaviz#127]
Contribute mdaviz to conda-forge.

_Originally posted by @prjemian in https://github.com/BCDA-APS/mdaviz/issues/113#issuecomment-2125276401_

**Comment by prjemian** [comment]
FYI: Just submitted contribution for new [*hklpy2*](https://prjemian.github.io/hklpy2) package:
https://github.com/conda-forge/staged-recipes/pull/26517

## Proposed procedure

* https://conda-forge.org/docs/maintainer/adding_pkgs/
* https://conda-forge.org/blog/2021/06/16/graykull-step-by-step/

1. `cd tmp`
1. install grayskull (I install in a new conda environment)
1. `grayskull pypi --strict-conda-forge mdaviz`
1. Fork https://github.com/conda-forge/staged-recipes to your personal github account: https://github.com/conda-forge/staged-recipes/
1. `git clone` from your fork and `cd` into the new directory
1. create (and checkout) a new branch: `mdaviz-package`
1. In the `recipes` directory, make a new `mdaviz` directory
1. `cp /tmp/mdaviz/meta.yaml recipes/mdaviz/`

You might need to add some additional info in the `about:` section of the `meta.yaml`.  Here's mine:

```yaml
about:
  home: https://prjemian.github.io/hklpy2
  summary: 2nd generation diffractometer controls for the Bluesky Framework.
  license: BSD-4-Clause
  license_file: LICENSE
  doc_url: https://prjemian.github.io/hklpy2
  dev_url: https://github.com/prjemian/hklpy2
```

9. Commit and push to your fork.
10. From your fork, open a PR to conda-forge.
11. Respond & resolve any problems.
12. Once it builds completely and is ready, add this comment: `@conda-forge/help-python @conda-forge/staged-recipes : This is ready for review, when you get a chance. Thanks!`
13. Wait for review (might take days).
14. Once approved, merge the PR (if not already merged).  In about an hour, your new `mdaviz` package should be ready on conda-forge.
